// <auto-generated />
namespace SelfieFriend.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialTwo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialTwo));
        
        string IMigrationMetadata.Id
        {
            get { return "201707060820459_initialTwo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
