// <auto-generated />
namespace SelfieFriend.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OfferingToOfferingCategoryRelations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OfferingToOfferingCategoryRelations));
        
        string IMigrationMetadata.Id
        {
            get { return "201805061027595_OfferingToOfferingCategoryRelations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
