// <auto-generated />
namespace SelfieFriend.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSubscribes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSubscribes));
        
        string IMigrationMetadata.Id
        {
            get { return "201805091355269_AddSubscribes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
